Create database employeedb;
\c employeedb
CREATE TABLE employees (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    address VARCHAR(155) NOT NULL,
    city VARCHAR(50) NOT NULL,
    state VARCHAR(2) NOT NULL,
    zip VARCHAR(50) NOT NULL,
    homephone VARCHAR(50) NOT NULL,
    cellphone VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL
);
INSERT INTO employees VALUES (0, 'Andrew', 'Webb', '123 blah blah', 'Baton Rouge', 'LA', 77000, '222-333-4444', '111-222-3333','awebb@aol.com');